### PR TITLE
Accept a DOM element as `container` option

### PR DESCRIPTION
**Pull request by duzun**
I want to be able to provide the DOM element of the container directly instead of through a selector.
In my use-case there is no unique selector for the container.

### CODE REVIEW

**Comment by Spope** [comment]
Makes sens, added a fix for this and updated the README. Will publish soon.

**Comment by duzun** [comment]
Thanks!

**Comment by Spope** [comment]
Published in v1.1.6

**Comment by duzun** [comment]
I've just tested the v1.1.6, works great!

**Pull request merged**
